import { ArrowUpRight, Boxes, ClipboardList, PackagePlus, Target } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { getReplenishmentWorkspace, type Stage5Option } from "@/lib/stage5";
import { saveReplenishmentTarget } from "@/app/(app)/stage5-actions";
import { DataTable } from "@/components/data-table";
import { EmptyState, FormField, InlineMessage } from "@/components/master-data-ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";

type SearchParams = Promise<{ error?: string; saved?: string }>;

function options(rows: Stage5Option[], name: string, placeholder: string) {
  return <Select name={name} defaultValue=""><option value="">{placeholder}</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.label}{row.code ? ` · ${row.code}` : ""}</option>)}</Select>;
}

export default async function ReplenishmentPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser();
  const params = await searchParams;
  const result = await getReplenishmentWorkspace();
  const canManage = user.roles.some((role) => ["director_admin", "inventory_manager", "sales_manager"].includes(role));
  const lowStock = result.rows.filter((row) => row.suggestedQuantity > 0).length;
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-forest-600">Stage 5 · Planning suggestions</p><h1 className="mt-2 flex items-center gap-3 font-display text-3xl font-bold tracking-tight text-ink"><PackagePlus className="h-8 w-8 text-forest-700" />Replenishment</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Use current branch stock, recent sell-through, target levels, lead time and eligible warehouse stock to plan replenishment. Suggestions never create automatic transfers.</p></div><a href="/sell-through" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-forest-200 bg-white px-4 text-sm font-semibold text-forest-800">View sell-through <ArrowUpRight className="h-4 w-4" /></a></div>
    {params.saved ? <InlineMessage>Replenishment target saved.</InlineMessage> : null}{params.error ? <InlineMessage kind="error">Check the target values, active retailer branch relationship and permissions.</InlineMessage> : null}{result.error ? <InlineMessage kind="error">{result.error}</InlineMessage> : null}
    <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-slate-500">Tracked targets</p><p className="mt-2 font-display text-3xl font-bold text-ink">{result.rows.length}</p><p className="mt-2 text-xs text-slate-500">Active branch / SKU target rows.</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-slate-500">Low-stock suggestions</p><p className="mt-2 font-display text-3xl font-bold text-amber-700">{lowStock}</p><p className="mt-2 text-xs text-slate-500">Rows where current stock is below target.</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-slate-500">Suggested units</p><p className="mt-2 font-display text-3xl font-bold text-forest-800">{result.rows.reduce((sum, row) => sum + row.suggestedQuantity, 0).toLocaleString()}</p><p className="mt-2 text-xs text-slate-500">Plan only; no automatic transfer.</p></CardContent></Card></div>
    {canManage ? <Card><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5 text-forest-700" />Set branch target</CardTitle><CardDescription>Targets are internal planning inputs. Product, SKU and branch relationships are validated in the database.</CardDescription></CardHeader><CardContent><form action={saveReplenishmentTarget} className="grid gap-4 md:grid-cols-2"><FormField label="Retailer" required>{options(result.refs.retailers, "retailerId", "Select retailer")}</FormField><FormField label="Branch" required>{options(result.refs.branches, "branchId", "Select branch")}</FormField><FormField label="Product" required>{options(result.refs.products, "productId", "Select product")}</FormField><FormField label="Sellable SKU" required>{options(result.refs.skus, "skuId", "Select SKU")}</FormField><FormField label="Minimum stock" required><Input type="number" name="minimumStock" min="0" step="1" required defaultValue="0" /></FormField><FormField label="Target stock" required><Input type="number" name="targetStock" min="0" step="1" required defaultValue="0" /></FormField><FormField label="Lead time (days)" required><Input type="number" name="leadTimeDays" min="0" step="1" required defaultValue="0" /></FormField><div className="flex items-end justify-end"><Button type="submit"><Target className="h-4 w-4" />Save target</Button></div></form></CardContent></Card> : null}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ClipboardList className="h-5 w-5 text-forest-700" />Recommendations</CardTitle><CardDescription>FEFO-eligible warehouse stock is shown as available planning stock. Warnings indicate when the warehouse cannot cover the suggested quantity.</CardDescription></CardHeader><CardContent>{result.rows.length === 0 ? <EmptyState title="No replenishment targets" description="Set a branch target to start producing useful suggestions." /> : <DataTable rows={result.rows} rowKey={(row) => row.targetId} columns={[{ key: "branch", header: "Branch", render: (row) => <div><p className="font-semibold">{row.branchName}</p><p className="mt-1 text-xs text-slate-500">{row.retailerName} · {row.branchCode}</p></div> }, { key: "sku", header: "Product / SKU", render: (row) => <div><p>{row.productName}</p><p className="mt-1 text-xs text-slate-500">{row.productCode} · {row.skuCode}</p></div> }, { key: "stock", header: "Branch stock", render: (row) => <div><p>{row.currentBranchStock.toLocaleString()} / {row.targetStock} target</p><p className="mt-1 text-xs text-slate-500">Min {row.minimumStock} · {row.avgDailySales.toFixed(2)} avg/day</p></div> }, { key: "suggested", header: "Suggested", render: (row) => <span className="font-semibold text-forest-800">{row.suggestedQuantity.toLocaleString()} units</span> }, { key: "warehouse", header: "Warehouse", render: (row) => <div><p>{row.availableWarehouseStock.toLocaleString()} eligible</p><p className="mt-1 text-xs text-slate-500">Lead time {row.leadTimeDays} days</p></div> }, { key: "status", header: "Planning status", render: (row) => <Badge tone={row.recommendationStatus === "ready for planning" ? "success" : "warning"}>{row.recommendationStatus}</Badge> }]} />}</CardContent></Card>
    <div className="rounded-2xl border border-forest-100 bg-forest-50/60 p-4 text-sm text-forest-800"><Boxes className="mr-2 inline h-4 w-4" />Replenishment is deliberately advisory in Stage 5. Review FEFO batches, shelf life and availability before using the Stage 4 transfer workflow.</div>
  </div>;
}
