import { FileText, Plus, ReceiptText, ShoppingCart } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { formatDate, formatLkr } from "@/lib/utils";
import { getSalesWorkspace, type Stage5Option } from "@/lib/stage5";
import { cancelRetailerSalesReport, cancelSalesOrder, confirmSalesOrder, createRetailerSalesReport, createSalesOrder, fulfilSalesOrder, postRetailerSalesReport } from "@/app/(app)/stage5-actions";
import { DataTable } from "@/components/data-table";
import { EmptyState, FormField, InlineMessage } from "@/components/master-data-ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type SearchParams = Promise<{ error?: string; saved?: string }>;

function notice(error?: string, saved?: string) {
  if (saved) return <InlineMessage>Stage 5 record saved successfully.</InlineMessage>;
  if (!error) return null;
  const messages: Record<string, string> = { duplicate: "That order or report reference already exists.", insufficient: "The operation would create negative stock. Review the available balance.", fefo: "A FEFO override reason is required for a later-expiring batch.", reference: "One of the selected records is inactive, expired or incorrectly linked.", validation: "Check the required fields, dates, quantities and prices.", "not-authorized": "Your role cannot perform this sales operation.", database: "The Stage 5 database migration is not available yet.", demo: "Demo mode is read-only. Connect the live Supabase session to record sales.", server: "The operation could not be completed. Check the server log for the detailed error." };
  return <InlineMessage kind="error">{messages[error] ?? messages.server}</InlineMessage>;
}

function options(rows: Stage5Option[], placeholder: string, name: string, productId?: string) {
  return <Select name={name} defaultValue=""><option value="">{placeholder}</option>{rows.filter((row) => !productId || row.productId === productId).map((row) => <option key={row.id} value={row.id}>{row.label}{row.code ? ` · ${row.code}` : ""}</option>)}</Select>;
}

export default async function SalesPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser();
  const params = await searchParams;
  const result = await getSalesWorkspace();
  const canManage = user.roles.some((role) => ["director_admin", "inventory_manager", "sales_manager"].includes(role));
  const canPost = user.roles.some((role) => ["director_admin", "inventory_manager"].includes(role));
  const canFulfil = user.roles.some((role) => ["director_admin", "inventory_manager", "warehouse_staff"].includes(role));
  const today = new Date().toISOString().slice(0, 10);
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-forest-600">Stage 5 · Revenue operations</p><h1 className="mt-2 flex items-center gap-3 font-display text-3xl font-bold tracking-tight text-ink"><ShoppingCart className="h-8 w-8 text-forest-700" />Sales & retailer reports</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Record online and direct sales, retailer sell-through and stock deductions without changing the immutable Stage 4 ledger.</p></div><div className="flex flex-wrap gap-2"><a href="/sell-through" className="inline-flex h-10 items-center justify-center rounded-xl border border-forest-200 bg-white px-4 text-sm font-semibold text-forest-800">Sell-through</a><a href="/returns" className="inline-flex h-10 items-center justify-center rounded-xl border border-forest-200 bg-white px-4 text-sm font-semibold text-forest-800">Returns</a></div></div>
    {notice(params.error, params.saved)}
    {result.error ? <InlineMessage kind="error">{result.error}</InlineMessage> : null}
    <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="p-5"><p className="text-sm text-slate-500">Sales records</p><p className="mt-2 font-display text-3xl font-bold text-ink">{result.orders.length}</p><p className="mt-2 text-xs text-slate-500">Pending, confirmed and fulfilled orders.</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-slate-500">Reported retailer units</p><p className="mt-2 font-display text-3xl font-bold text-ink">{result.reports.reduce((sum, row) => sum + row.quantitySold, 0).toLocaleString()}</p><p className="mt-2 text-xs text-slate-500">Sell-through reports in the current view.</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-slate-500">Sales value</p><p className="mt-2 font-display text-3xl font-bold text-ink">{formatLkr(result.orders.reduce((sum, row) => sum + row.totalValue, 0))}</p><p className="mt-2 text-xs text-slate-500">Discounts remain visible for authorized finance roles.</p></CardContent></Card></div>
    {canManage ? <Card id="sale-form"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="h-5 w-5 text-forest-700" />Record a sale</CardTitle><CardDescription>Saving creates a pending document. Stock is deducted only when an authorized user fulfils it.</CardDescription></CardHeader><CardContent><form action={createSalesOrder} className="grid gap-4 md:grid-cols-2"><FormField label="Order / reference" required><Input name="orderNumber" required placeholder="GL-ONLINE-2026-0001" /></FormField><FormField label="Sale date" required><Input type="date" name="saleDate" required defaultValue={today} /></FormField><FormField label="Sales channel" required><Select name="salesChannel" defaultValue="online_store" required><option value="online_store">GoodLivin online store</option><option value="retailer_branch">Retailer branch</option><option value="direct_sale">Direct / manual sale</option><option value="event_pop_up">Event / pop-up</option></Select></FormField><FormField label="Fulfilment location" required>{options(result.refs.locations, "Select active location", "fulfilmentLocationId")}</FormField><FormField label="Product" required>{options(result.refs.products, "Select product", "productId")}</FormField><FormField label="Sellable SKU" required>{options(result.refs.skus, "Select SKU", "skuId")}</FormField><FormField label="Batch (optional)" hint="Leave blank to use FEFO at fulfilment.">{options(result.refs.batches, "FEFO at fulfilment", "batchId")}</FormField><FormField label="Quantity" required><Input type="number" name="quantity" min="1" step="1" required defaultValue="1" /></FormField><FormField label="Selling price (LKR)" required><Input type="number" name="sellingPrice" min="0" step="0.01" required defaultValue="0" /></FormField><FormField label="Discount (LKR)"><Input type="number" name="discount" min="0" step="0.01" defaultValue="0" /></FormField><FormField label="Retailer (branch channel)">{options(result.refs.retailers, "Not applicable", "retailerId")}</FormField><FormField label="Branch (branch channel)">{options(result.refs.branches, "Not applicable", "branchId")}</FormField><FormField label="Customer name"><Input name="customerName" placeholder="Optional" /></FormField><FormField label="Customer contact"><Input name="customerContact" placeholder="Optional phone or email" /></FormField><FormField label="Notes"><Textarea name="notes" placeholder="Order notes, delivery context or correction context" /></FormField><div className="flex items-center justify-end md:col-span-2"><Button type="submit"><Plus className="h-4 w-4" />Save pending sale</Button></div></form></CardContent></Card> : null}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptText className="h-5 w-5 text-forest-700" />Retailer sell-through report</CardTitle><CardDescription>Record sold, returned, damaged and expired quantities for one retailer branch and period. Inventory posting is a separate controlled action.</CardDescription></CardHeader><CardContent>{canManage ? <form action={createRetailerSalesReport} className="grid gap-4 md:grid-cols-2"><FormField label="Report / reference" required><Input name="reportNumber" required placeholder="RPT-CARG-2026-001" /></FormField><FormField label="Report date" required><Input type="date" name="reportDate" required defaultValue={today} /></FormField><FormField label="Period start" required><Input type="date" name="periodStart" required defaultValue={today} /></FormField><FormField label="Period end" required><Input type="date" name="periodEnd" required defaultValue={today} /></FormField><FormField label="Retailer" required>{options(result.refs.retailers, "Select retailer", "retailerId")}</FormField><FormField label="Branch" required>{options(result.refs.branches, "Select branch", "branchId")}</FormField><FormField label="Product" required>{options(result.refs.products, "Select product", "productId")}</FormField><FormField label="SKU" required>{options(result.refs.skus, "Select SKU", "skuId")}</FormField><FormField label="Batch (optional)" hint="If blank, posting uses FEFO stock at the branch.">{options(result.refs.batches, "FEFO at posting", "batchId")}</FormField><FormField label="Sold quantity"><Input type="number" name="quantitySold" min="0" step="1" defaultValue="0" /></FormField><FormField label="Returns sent back"><Input type="number" name="returnsQuantity" min="0" step="1" defaultValue="0" /></FormField><FormField label="Damaged quantity"><Input type="number" name="damagedQuantity" min="0" step="1" defaultValue="0" /></FormField><FormField label="Expired quantity"><Input type="number" name="expiredQuantity" min="0" step="1" defaultValue="0" /></FormField><FormField label="Return destination">{options(result.refs.locations.filter((row) => ["warehouse", "main_warehouse", "office_stock"].includes(String(row.locationType))), "Default warehouse", "returnLocationId")}</FormField><FormField label="Damaged destination">{options(result.refs.locations, "Choose if needed", "damagedLocationId")}</FormField><FormField label="Expired destination">{options(result.refs.locations, "Choose if needed", "expiredLocationId")}</FormField><FormField label="Notes"><Textarea name="notes" placeholder="Reporting source, reconciliation notes or attachment reference" /></FormField><div className="flex items-center justify-end md:col-span-2"><Button type="submit"><FileText className="h-4 w-4" />Save pending report</Button></div></form> : <p className="text-sm text-slate-500">Your role can view retailer reports but cannot create them.</p>}</CardContent></Card>
    <div><div className="mb-3 flex items-end justify-between"><div><h2 className="font-display text-xl font-bold text-ink">Sales history</h2><p className="mt-1 text-sm text-slate-500">Cancellation before fulfilment creates no stock movement. Fulfilment and refunds are ledger-linked.</p></div><span className="text-sm text-slate-500">{result.orders.length} record{result.orders.length === 1 ? "" : "s"}</span></div>{result.orders.length === 0 ? <EmptyState title="No sales recorded" description="Create a pending sale to begin the controlled fulfilment workflow." /> : <DataTable rows={result.orders} rowKey={(row) => row.id} columns={[{ key: "order", header: "Order", render: (row) => <div><p className="font-semibold">{row.orderNumber}</p><p className="mt-1 text-xs text-slate-500">{formatDate(row.saleDate)} · {row.salesChannel}</p></div> }, { key: "stock", header: "Stock", render: (row) => <div><p>{row.productName}</p><p className="mt-1 text-xs text-slate-500">{row.skuCode} · {row.batchNumber ?? "FEFO pending"}</p></div> }, { key: "location", header: "Location", render: (row) => row.locationName }, { key: "value", header: "Value", render: (row) => <div><p>{row.quantity.toLocaleString()} units</p><p className="mt-1 text-xs text-slate-500">{formatLkr(row.totalValue)} · discount {formatLkr(row.discount)}</p></div> }, { key: "status", header: "Status", render: (row) => <Badge tone={row.status === "fulfilled" ? "success" : row.status === "cancelled" ? "danger" : row.status === "refunded" ? "warning" : "info"}>{row.status}</Badge> }, { key: "actions", header: "Actions", className: "text-right", render: (row) => <div className="flex flex-wrap justify-end gap-2">{row.status === "pending" && canManage ? <form action={confirmSalesOrder}><input type="hidden" name="id" value={row.id} /><Button type="submit" size="sm" variant="secondary">Confirm</Button></form> : null}{row.status === "confirmed" && canFulfil ? <form action={fulfilSalesOrder} className="flex gap-1"><input type="hidden" name="id" value={row.id} /><Input name="overrideReason" className="h-9 w-32 text-xs" placeholder="FEFO reason" /><Button type="submit" size="sm">Fulfil</Button></form> : null}{["pending", "confirmed"].includes(row.status) && canManage ? <form action={cancelSalesOrder}><input type="hidden" name="id" value={row.id} /><input type="hidden" name="reason" value="Cancelled by authorised user" /><Button type="submit" size="sm" variant="secondary">Cancel</Button></form> : null}</div> }]} />}</div>
    <div><div className="mb-3 flex items-end justify-between"><div><h2 className="font-display text-xl font-bold text-ink">Retailer reports</h2><p className="mt-1 text-sm text-slate-500">Posted reports create one immutable movement per reported stock component.</p></div><span className="text-sm text-slate-500">{result.reports.length} report{result.reports.length === 1 ? "" : "s"}</span></div>{result.reports.length === 0 ? <EmptyState title="No retailer reports" description="Retailer branch reports will appear here after they are recorded." /> : <DataTable rows={result.reports} rowKey={(row) => row.id} columns={[{ key: "report", header: "Report", render: (row) => <div><p className="font-semibold">{row.reportNumber}</p><p className="mt-1 text-xs text-slate-500">{formatDate(row.reportDate)} · {formatDate(row.periodStart)}–{formatDate(row.periodEnd)}</p></div> }, { key: "branch", header: "Retailer / branch", render: (row) => <div><p>{row.retailerName}</p><p className="mt-1 text-xs text-slate-500">{row.branchName}</p></div> }, { key: "stock", header: "Stock", render: (row) => <div><p>{row.productName}</p><p className="mt-1 text-xs text-slate-500">{row.skuCode} · {row.batchNumber ?? "FEFO pending"}</p></div> }, { key: "quantities", header: "Reported units", render: (row) => <div className="text-xs"><p>Sold {row.quantitySold} · Return {row.returnsQuantity}</p><p className="mt-1 text-slate-500">Damaged {row.damagedQuantity} · Expired {row.expiredQuantity}</p></div> }, { key: "status", header: "Status", render: (row) => <Badge tone={row.status === "posted" ? "success" : row.status === "cancelled" ? "danger" : "info"}>{row.status}</Badge> }, { key: "actions", header: "Actions", className: "text-right", render: (row) => <div className="flex flex-wrap justify-end gap-2">{row.status === "pending" && canPost ? <form action={postRetailerSalesReport} className="flex gap-1"><input type="hidden" name="id" value={row.id} /><Input name="overrideReason" className="h-9 w-32 text-xs" placeholder="FEFO reason" /><Button type="submit" size="sm">Post</Button></form> : null}{row.status === "pending" && canManage ? <form action={cancelRetailerSalesReport}><input type="hidden" name="id" value={row.id} /><input type="hidden" name="reason" value="Cancelled by authorised user" /><Button type="submit" size="sm" variant="secondary">Cancel</Button></form> : null}</div> }]} />}</div>
    <p className="text-xs text-slate-400">All posted deductions, overrides, cancellations and refunds are recorded in the existing audit log. Stage 5 does not create retailer logins or automatic transfers.</p>
  </div>;
}
