import Link from "next/link";
import { ArrowLeft, Edit3, Factory, Plus } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { getManufacturerWorkspace, getSupplierProductCatalog } from "@/lib/master-data";
import { getProcurementReferences } from "@/lib/procurement";
import { archiveManufacturer, saveManufacturer } from "@/app/(app)/master-data-actions";
import { ArchiveButton, EmptyState, FilterBar, FormField, InlineMessage } from "@/components/master-data-ui";
import { DataTable } from "@/components/data-table";
import { StatusBadge } from "@/components/status-badge";
import { SourcingCatalogPanel } from "@/components/sourcing-catalog-panel";
import { Badge } from "@/components/ui/badge";
import { SubmitButton } from "@/components/ui/submit-button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type SearchParams = Promise<{ q?: string; status?: string; edit?: string; saved?: string; demo?: string; error?: string }>;

export default async function ManufacturersPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser();
  const params = await searchParams;
  const [result, catalog, refs] = await Promise.all([
    getManufacturerWorkspace({ q: params.q, status: params.status ?? "active" }),
    getSupplierProductCatalog({ owner: "manufacturer", q: params.q, status: params.status ?? "active" }),
    getProcurementReferences(),
  ]);
  const canManage = user.roles.some((role) => role === "director_admin" || role === "inventory_manager");
  const editing = params.edit && params.edit !== "new" ? result.data.find((row) => row.id === params.edit) : undefined;
  const notice = params.error ? <InlineMessage kind="error">The manufacturer change could not be saved. Check the fields and permissions.</InlineMessage> : params.demo ? <InlineMessage kind="info">Demo mode is read-only; this is a preview.</InlineMessage> : params.saved === "catalog" ? <InlineMessage>Manufacturer SKU source saved and audit recorded.</InlineMessage> : params.saved ? <InlineMessage>Manufacturer saved and audit recorded.</InlineMessage> : null;
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/products" className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-forest-700"><ArrowLeft className="h-4 w-4" />Back to products</Link><p className="text-sm font-semibold uppercase tracking-[0.18em] text-forest-600">Catalogue reference data</p><h1 className="mt-2 flex items-center gap-3 font-display text-3xl font-bold tracking-tight text-ink"><Factory className="h-8 w-8 text-forest-700" />Manufacturers</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Keep production-source contacts, lead times, MOQs, tax details and terms ready for purchasing.</p></div>{canManage ? <Link href="/products/manufacturers?edit=new#manufacturer-form" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-forest-700 px-4 text-sm font-semibold text-white"><Plus className="h-4 w-4" />New manufacturer</Link> : <Badge tone="neutral">Read-only reference data</Badge>}</div>
    {notice}
    <div className="flex gap-2 border-b border-forest-100 pb-3"><Link href="/products/manufacturers" className="rounded-xl bg-forest-700 px-3 py-2 text-sm font-semibold text-white">Manufacturers</Link><Link href="/products/suppliers" className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-500 hover:bg-forest-50 hover:text-forest-800">Suppliers</Link></div>
    <FilterBar action="/products/manufacturers" query={params.q} status={params.status ?? "active"} />
    {result.error ? <InlineMessage kind="error">{result.error}</InlineMessage> : result.data.length === 0 ? <EmptyState title="No manufacturers match" description="Adjust the filters or add a manufacturer reference record." /> : <DataTable rows={result.data} rowKey={(row) => row.id} columns={[{ key: "name", header: "Manufacturer", render: (row) => <div><p className="font-semibold">{row.name}</p><p className="mt-1 text-xs text-slate-500">{row.code ?? "No code"} · {row.country ?? "Country not set"}</p><p className="mt-1 text-xs text-slate-400">Updated {new Date(row.updatedAt).toLocaleDateString()}</p></div> }, { key: "contact", header: "Contact", render: (row) => <div><p>{row.contactName ?? "—"}</p><p className="mt-1 text-xs text-slate-500">{row.contactEmail ?? row.contactPhone ?? "No contact details"}</p></div> }, { key: "terms", header: "Terms", render: (row) => <div><p>{row.standardLeadTimeDays}d lead time · MOQ {row.minimumOrderQuantity}</p><p className="mt-1 text-xs text-slate-500">{row.defaultCurrency} · {row.paymentTerms ?? "Terms not set"}</p></div> }, { key: "status", header: "Status", render: (row) => <StatusBadge status={row.status} /> }, { key: "actions", header: "Actions", className: "text-right", render: (row) => canManage ? <div className="flex justify-end gap-2"><Link href={`/products/manufacturers?edit=${row.id}#manufacturer-form`} className="inline-flex h-9 items-center gap-1 rounded-xl border border-forest-200 px-3 text-xs font-semibold text-forest-800"><Edit3 className="h-3.5 w-3.5" />Edit</Link>{row.status === "active" ? <ArchiveButton action={archiveManufacturer} id={row.id} recordLabel={row.name} /> : null}</div> : <span className="text-xs text-slate-400">Read-only</span> }]} />}
    {canManage && params.edit ? <Card id="manufacturer-form"><CardHeader><CardTitle>{editing ? "Edit manufacturer" : "Add manufacturer"}</CardTitle><CardDescription>Capture production and sourcing context for inbound planning.</CardDescription></CardHeader><CardContent><form action={saveManufacturer} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="id" value={editing?.id ?? ""} /><FormField label="Name" required><Input name="name" required defaultValue={editing?.name ?? ""} placeholder="GoodLivin Labs" /></FormField><FormField label="Code"><Input name="code" defaultValue={editing?.code ?? ""} placeholder="GL-LABS" /></FormField><FormField label="Contact name"><Input name="contactName" defaultValue={editing?.contactName ?? ""} /></FormField><FormField label="Contact email"><Input name="contactEmail" type="email" defaultValue={editing?.contactEmail ?? ""} /></FormField><FormField label="Contact phone"><Input name="contactPhone" defaultValue={editing?.contactPhone ?? ""} /></FormField><FormField label="Country"><Input name="country" defaultValue={editing?.country ?? "Sri Lanka"} /></FormField><FormField label="Address"><Input name="addressLine1" defaultValue={editing?.addressLine1 ?? ""} /></FormField><FormField label="City"><Input name="city" defaultValue={editing?.city ?? ""} /></FormField><FormField label="Currency"><Input name="defaultCurrency" maxLength={3} defaultValue={editing?.defaultCurrency ?? "LKR"} /></FormField><FormField label="Standard lead time (days)"><Input name="standardLeadTimeDays" type="number" min="0" defaultValue={editing?.standardLeadTimeDays ?? 0} /></FormField><FormField label="Minimum order quantity"><Input name="minimumOrderQuantity" type="number" min="0" defaultValue={editing?.minimumOrderQuantity ?? 0} /></FormField><FormField label="Payment terms"><Input name="paymentTerms" defaultValue={editing?.paymentTerms ?? ""} /></FormField><FormField label="Tax / registration details"><Input name="taxRegistrationDetails" defaultValue={editing?.taxRegistrationDetails ?? ""} /></FormField><FormField label="Internal notes"><Textarea name="notes" defaultValue={editing?.notes ?? ""} /></FormField><div className="flex justify-end gap-2 sm:col-span-2"><Link href="/products/manufacturers" className="inline-flex h-10 items-center px-3 text-sm font-semibold text-slate-500">Cancel</Link><SubmitButton><Plus className="h-4 w-4" />{editing ? "Save changes" : "Create manufacturer"}</SubmitButton></div></form></CardContent></Card> : <Card><CardHeader><CardTitle>Reference data</CardTitle><CardDescription>Manufacturers are shared by product records and can be archived without breaking historical links. Changes are captured by the shared audit log.</CardDescription></CardHeader></Card>}
    <SourcingCatalogPanel ownerType="manufacturer" rows={catalog.data} owners={refs.manufacturers} products={refs.products} skus={refs.skus} canManage={canManage} error={catalog.error ?? refs.error} />
  </div>;
}
