import Link from "next/link";
import { Archive, Edit3, MapPin, PackageCheck, Plus, Scale, Truck } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { getLocationWorkspace, type LocationType } from "@/lib/master-data";
import { getInventoryWorkspace } from "@/lib/stock-operations";
import { archiveLocation, saveLocation } from "@/app/(app)/master-data-actions";
import { DataTable } from "@/components/data-table";
import { ArchiveButton, EmptyState, FilterBar, FormField, InlineMessage } from "@/components/master-data-ui";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { SubmitButton } from "@/components/ui/submit-button";
import { StatusBadge } from "@/components/status-badge";

type SearchParams = Promise<{ q?: string; status?: string; type?: string; edit?: string; saved?: string; demo?: string; error?: string; productId?: string; skuId?: string; locationId?: string; retailerId?: string; qualityStatus?: string }>;

const locationLabels: Record<LocationType, string> = { warehouse: "Warehouse (legacy)", main_warehouse: "Main warehouse", office_stock: "Office stock", online_order_stock: "Online-order stock", event_stock: "Event stock", retailer_branch: "Retailer branch", sample_influencer_stock: "Sample / influencer stock", damaged_stock: "Damaged stock", quarantine: "Quarantine (legacy)", quarantine_stock: "Quarantine stock", expired_stock: "Expired stock", transit: "Transit", production: "Production" };
const errorMessages: Record<string, string> = { "duplicate-code": "That location code is already in use.", validation: "Check the code, name, type, and required retailer-branch relationships.", reference: "The selected retailer or branch is no longer available.", "not-authorized": "Your role can view locations but cannot manage them.", server: "The location change could not be saved." };

function LocationForm({ location, retailers, branches }: { location?: Awaited<ReturnType<typeof getLocationWorkspace>>["data"]["locations"][number]; retailers: Awaited<ReturnType<typeof getLocationWorkspace>>["data"]["retailers"]; branches: Awaited<ReturnType<typeof getLocationWorkspace>>["data"]["branches"] }) {
  return <Card id="location-form"><CardHeader><CardTitle>{location ? "Edit inventory location" : "Add inventory location"}</CardTitle><CardDescription>Retailer-branch locations must reference a branch belonging to the selected retailer. Other types stay GoodLivin-wide.</CardDescription></CardHeader><CardContent><form action={saveLocation} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={location?.id ?? ""} /><FormField label="Location code" required hint="Must be unique; existing codes remain valid."><Input name="code" required defaultValue={location?.code ?? ""} placeholder="WH-KOT" /></FormField><FormField label="Location name" required><Input name="name" required defaultValue={location?.name ?? ""} placeholder="Kotte Main Warehouse" /></FormField><FormField label="Location type" required><Select name="locationType" required defaultValue={location?.locationType ?? "main_warehouse"}>{Object.entries(locationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></FormField><FormField label="Retailer"><Select name="retailerId" defaultValue={location?.retailerId ?? ""}><option value="">No retailer scope</option>{retailers.map((retailer) => <option key={retailer.id} value={retailer.id}>{retailer.name} · {retailer.code}</option>)}</Select></FormField><FormField label="Retailer branch" hint="Required when type is Retailer branch."><Select name="branchId" defaultValue={location?.branchId ?? ""}><option value="">No branch relationship</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name} · {branch.code}</option>)}</Select></FormField><FormField label="Address"><Input name="addressLine1" defaultValue={location?.addressLine1 ?? ""} placeholder="Address line" /></FormField><FormField label="City"><Input name="city" defaultValue={location?.city ?? ""} placeholder="Colombo" /></FormField><div className="flex items-center justify-end gap-2 md:col-span-2"><Link href="/inventory" className="inline-flex h-10 items-center px-3 text-sm font-semibold text-slate-500">Cancel</Link><SubmitButton><Plus className="h-4 w-4" />{location ? "Save changes" : "Create location"}</SubmitButton></div></form></CardContent></Card>;
}

export default async function InventoryPage({ searchParams }: { searchParams: SearchParams }) {
  const user = await requireUser();
  const params = await searchParams;
  const [result, balanceResult] = await Promise.all([
    getLocationWorkspace({ q: params.q, status: params.status ?? "active", type: params.type }),
    getInventoryWorkspace({ q: params.q, productId: params.productId, skuId: params.skuId, locationId: params.locationId, retailerId: params.retailerId, qualityStatus: params.qualityStatus }),
  ]);
  const canManage = user.roles.some((role) => role === "director_admin" || role === "inventory_manager");
  const editing = params.edit && params.edit !== "new" ? result.data.locations.find((row) => row.id === params.edit) : undefined;
  const notice = params.error ? <InlineMessage kind="error">{errorMessages[params.error] ?? "The request could not be completed."}</InlineMessage> : params.demo ? <InlineMessage kind="info">Demo mode is read-only; this is a preview.</InlineMessage> : params.saved ? <InlineMessage>Location saved and audit recorded.</InlineMessage> : null;
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-forest-600">Stage 4 · Inventory control</p><h1 className="mt-2 flex items-center gap-3 font-display text-3xl font-bold tracking-tight text-ink"><Scale className="h-8 w-8 text-forest-700" />Live inventory</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Balances are calculated from immutable movements by SKU, batch, location and retailer branch.</p></div><div className="flex flex-wrap gap-2"><Link href="/receiving" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-forest-700 px-4 text-sm font-semibold text-white"><PackageCheck className="h-4 w-4" />Receive stock</Link><Link href="/transfers" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-forest-200 bg-white px-4 text-sm font-semibold text-forest-800"><Truck className="h-4 w-4" />Transfers</Link></div></div>
    {notice}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Total stock", balanceResult.summary.totalUnits, "units"], ["Available", balanceResult.summary.availableUnits, "sellable units"], ["Quarantined", balanceResult.summary.quarantinedUnits, "units"], ["Damaged", balanceResult.summary.damagedUnits, "units"], ["Expired", balanceResult.summary.expiredUnits, "units"], ["SKU warnings", balanceResult.summary.warningCount, "attention needed"]].map(([label, value, suffix]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">{label}</p><p className="mt-2 font-display text-2xl font-bold text-ink">{Number(value).toLocaleString()}</p><p className="mt-1 text-xs text-slate-500">{suffix}</p></CardContent></Card>)}</div>
    <Card><CardContent className="p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-display text-xl font-bold text-ink">Balance filters</h2><p className="mt-1 text-sm text-slate-500">Search by product, SKU, batch, location, retailer branch or quality status.</p></div><Link href="/movements" className="text-sm font-semibold text-forest-700">View ledger</Link></div><form action="/inventory" method="get" className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><Input name="q" defaultValue={params.q} placeholder="Search inventory" /><Select name="productId" defaultValue={params.productId ?? ""}><option value="">All products</option>{balanceResult.products.map((row) => <option key={row.id} value={row.id}>{row.label} · {row.code}</option>)}</Select><Select name="skuId" defaultValue={params.skuId ?? ""}><option value="">All SKUs</option>{balanceResult.skus.map((row) => <option key={row.id} value={row.id}>{row.label} · {row.code}</option>)}</Select><Select name="locationId" defaultValue={params.locationId ?? ""}><option value="">All locations</option>{balanceResult.locations.map((row) => <option key={row.id} value={row.id}>{row.label} · {row.code}</option>)}</Select><Select name="retailerId" defaultValue={params.retailerId ?? ""}><option value="">All retailers</option>{balanceResult.retailers.map((row) => <option key={row.id} value={row.id}>{row.label}</option>)}</Select><div className="flex gap-2"><Select name="qualityStatus" defaultValue={params.qualityStatus ?? "all"} className="min-w-0 flex-1"><option value="all">All quality</option><option value="approved">Approved</option><option value="pending">Pending</option><option value="quarantined">Quarantined</option><option value="rejected">Rejected</option><option value="recalled">Recalled</option></Select><Button type="submit" variant="secondary">Apply</Button></div></form></CardContent></Card>
    {balanceResult.warnings.length > 0 ? <div className="grid gap-3 md:grid-cols-2">{balanceResult.warnings.map((warning) => <div key={`${warning.productId}-${warning.severity}`} className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">{warning.productName} · {warning.productCode}</p><p className="mt-1">{warning.quantity.toLocaleString()} units on hand; {warning.severity === "minimum" ? `minimum level is ${warning.minimumStockLevel.toLocaleString()}` : `reorder level is ${warning.reorderLevel.toLocaleString()}`}.</p></div>)}</div> : null}
    {balanceResult.error ? <InlineMessage kind="error">{balanceResult.error}</InlineMessage> : balanceResult.balances.length === 0 ? <EmptyState title="No live balances yet" description="Receive approved batches or complete a transfer to populate the immutable inventory ledger." /> : <DataTable rows={balanceResult.balances} rowKey={(row) => row.id} columns={[{ key: "stock", header: "Product / SKU", render: (row) => <div><p className="font-semibold">{row.productName}</p><p className="mt-1 text-xs text-slate-500">{row.productCode} · {row.skuName} · {row.skuCode}</p></div> }, { key: "batch", header: "Batch / expiry", render: (row) => <div><p>{row.batchNumber}</p><p className="mt-1 text-xs text-slate-500">Expires {new Date(`${row.expiresOn}T00:00:00Z`).toLocaleDateString("en-LK", { dateStyle: "medium" })}</p></div> }, { key: "location", header: "Location", render: (row) => <div><p>{row.locationName}</p><p className="mt-1 text-xs text-slate-500">{row.branchName ?? row.retailerName ?? row.locationCode}</p></div> }, { key: "quantity", header: "On hand", render: (row) => <div><p>{row.quantityOnHand.toLocaleString()} units</p><p className="mt-1 text-xs text-forest-700">{row.availableQuantity.toLocaleString()} available</p></div> }, { key: "quality", header: "Quality", render: (row) => <Badge tone={row.qualityStatus === "approved" ? "success" : "warning"}>{row.qualityStatus}</Badge> }, { key: "last", header: "Last movement", render: (row) => row.lastMovementAt ? new Date(row.lastMovementAt).toLocaleDateString("en-LK", { dateStyle: "medium" }) : "—" }]} />}
    <div className="rounded-2xl border border-forest-100 bg-forest-50/60 p-4 text-sm text-forest-800"><Archive className="mr-2 inline h-4 w-4" />Balances are derived from the ledger; users cannot type over them. Use receipts, transfers or controlled adjustments to change stock.</div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-forest-600">Stage 2 · Master data</p><h2 className="mt-2 flex items-center gap-2 font-display text-2xl font-bold tracking-tight text-ink"><MapPin className="h-6 w-6 text-forest-700" />Inventory locations</h2><p className="mt-1 text-sm text-slate-500">Manage active warehouses, stock pools, events and retailer branch locations without deleting historical references.</p></div>{canManage ? <Link href="/inventory?edit=new#location-form" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-forest-200 bg-white px-4 text-sm font-semibold text-forest-800 hover:bg-forest-50"><Plus className="h-4 w-4" />New location</Link> : <Badge tone="neutral">Read-only locations</Badge>}</div>
    <div className="rounded-2xl border border-forest-100 bg-forest-50/60 p-4 text-sm text-forest-800"><Archive className="mr-2 inline h-4 w-4" />The location master remains archive-only and is now used by the live ledger.</div><FilterBar action="/inventory" query={params.q} status={params.status ?? "active"}><Select name="type" defaultValue={params.type ?? "all"} className="sm:w-56"><option value="all">All location types</option>{Object.entries(locationLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></FilterBar>
    <div className="flex items-center justify-between"><div><h2 className="font-display text-xl font-bold text-ink">Location register</h2><p className="mt-1 text-sm text-slate-500">{result.error ? "Unable to load locations." : `${result.data.locations.length} location${result.data.locations.length === 1 ? "" : "s"} shown`}</p></div>{!canManage ? <p className="text-xs text-slate-400">Your role can view scoped locations but cannot change them.</p> : null}</div>{result.error ? <InlineMessage kind="error">{result.error}</InlineMessage> : result.data.locations.length === 0 ? <EmptyState title="No locations match" description="Adjust the filters or create the first location master record." /> : <DataTable rows={result.data.locations} rowKey={(row) => row.id} columns={[{ key: "location", header: "Location", render: (row) => <div><p className="font-semibold">{row.name}</p><p className="mt-1 text-xs text-slate-500">{row.code}</p></div> }, { key: "type", header: "Type", render: (row) => <Badge tone={row.locationType === "retailer_branch" ? "info" : "sage"}>{locationLabels[row.locationType]}</Badge> }, { key: "scope", header: "Relationship", render: (row) => <div className="text-sm"><p>{row.branchName ?? row.retailerName ?? "GoodLivin-wide"}</p><p className="mt-1 text-xs text-slate-500">{row.city ?? row.addressLine1 ?? "No address"}</p></div> }, { key: "status", header: "Status", render: (row) => <StatusBadge status={row.status} /> }, { key: "actions", header: "Actions", className: "text-right", render: (row) => canManage ? <div className="flex justify-end gap-2"><Link href={`/inventory?edit=${row.id}#location-form`} className="inline-flex h-9 items-center gap-1 rounded-xl border border-forest-200 px-3 text-xs font-semibold text-forest-800 hover:bg-forest-50"><Edit3 className="h-3.5 w-3.5" />Edit</Link>{row.status === "active" ? <ArchiveButton action={archiveLocation} id={row.id} recordLabel={row.name} /> : null}</div> : <span className="text-xs text-slate-400">Read-only</span> }]} />}{canManage && params.edit ? <LocationForm location={editing} retailers={result.data.retailers} branches={result.data.branches} /> : null}
  </div>;
}
